version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    groups:
      npm-deps:
        update-types:
          - major
          - minor
          - patch
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    target-branch: "main"
    schedule:
      interval: "weekly"
    groups:
      github-actions-deps:
        update-types:
          - major
          - minor
          - patch
        patterns:
          - "*"
