name: release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions: {}

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Setup Node
        uses: ./tooling/github/setup-node

      - name: Storing release version for changeset
        id: release_version
        run: echo "VALUE=$(./.github/scripts/print_release_version.sh)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Creating release pull request or publishing release to npm registry
        id: changesets
        uses: dotansimha/changesets-action@v1.5.2
        with:
          publish: pnpm run release
          version: pnpm run version
          commit: "chore: new release"
          title: "chore: new release candidate"
          createGithubReleases: aggregate
          githubReleaseName: v${{ steps.release_version.outputs.VALUE }}
          githubTagName: v${{ steps.release_version.outputs.VALUE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
