name: test-and-lint.yml
on:
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Setup Node
        uses: ./tooling/github/setup-node

      - name: Test and Lint Affected
        uses: turbo run test lint --affected
